- name: Create a virtual machine on ESXi
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    esxi_hostname: "myesxi"
    esxi_username: "root"
    esxi_password: "root123$"
    vm_guestid: "centos64Guest"
    vm_name: "test"
    datastore: "datastore1"
    network: "VM Network"
    vm_cpu: 2
    vm_memory_mb: 2048
  tasks:
    - name: Create a virtual machine
      vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        name: "{{ vm_name }}"
        folder: "/"
        datastore: "{{ datastore }}"
        guest_id: "{{ vm_guestid }}"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_cpu }}"
          scsi: paravirtual
        disk:
          - size_gb: 16
            type: thin
            datastore: "{{ datastore }}"
        networks:
          - name: "{{ network }}"
            device_type: vmxnet3
            start_connected: true
            type: static
        state: poweredoff
